name: 'Code Checks'

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.1', '8.2', '8.3', '8.4' ]

    name: PHP ${{ matrix.php }} tests

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Composer install
        run: composer install --no-progress

      - name: Run tests
        run: vendor/bin/phpunit

  code_style:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.1' ]

    name: PHP ${{ matrix.php }} code style

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - name: Composer install
        run: composer install --no-progress

      - name: Run CS fixer
        run: PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer check --format=txt --verbose --diff --allow-risky=yes --config=.php-cs-fixer.dist.php

  phpstan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.1' ]

    name: PHP ${{ matrix.php }} phpstan

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Composer install
        run: composer install --no-progress

      - name: Run phpstan
        run: vendor/bin/phpstan analyse -c phpstan.${{ matrix.php }}.neon
  composer_dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.1' ]

    name: PHP ${{ matrix.php }} problematic dependencies

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - name: Composer install
        run: composer install --no-progress

      - name: Run dependency analyzer
        run: vendor/bin/composer-dependency-analyser
#        run: vendor/bin/composer-dependency-analyser --config=composer-dependency-analyser.php
